version: 0.0
Resources:
- TargetService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: "arn:aws:ecs:ap-northeast-1:Account-it:task-definition/duc-ecr-blue-green-app:1"
      LoadBalancerInfo:
        ContainerName: "duc-ecr-blue-green-app"
        ContainerPort: 80
      PlatformVersion: "LATEST"
